# -*- coding: utf-8 -*-
"""CSE423 {Lab- 03}

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECbgmSkUBbFRdtUvwxqOca-u5cPXaPjz

#***LAB- 03***
"""

from OpenGL.GL import *
from OpenGL.GLUT import *
from OpenGL.GLU import *
import time,math,random
from collections import deque

class window:
    width = 1200
    heigth = 800
    camera_pos = (0,580,500,0)
    cemera_state = 0
    grid_len = 700
    cam_v = (0,0)

class Game:
    score = 0
    life = 5
    bullet_miss = 0
    end = False
    cheat_mode = False
    pause = False

fovY = 120
enemie_scale = 0

class Position:
    player = (0,0,0,0)
    enemies = [(random.randint(-window.grid_len+50,window.grid_len-50),random.randint(-window.grid_len+50,window.grid_len-50),0) for i in range(5)]
    bullet = deque()

# Colors
class color:
    floor = (
        (0,0.2,0),
        (1,1,1)
    )
    walls = (
        (0,0,1),
        (1,0,0),
        (0,1,0),
        (1,0,1)
    )
    enemie = (
        (0,0,0),
        (1,0,0),
    )
    player = (
        (0,0,0),
        (0,0,0.3),
        (250, 219, 97),
        (0,0,1),
        (0.3,0.3,0.3),
    )
    bullet = (1,0,0)

def restart():
    Position.player = (0,0,0,0)
    Position.enemies = [(random.randint(-window.grid_len+50,window.grid_len-50),random.randint(-window.grid_len+50,window.grid_len-50),0) for i in range(5)]
    Position.bullet = deque()
    Game.score = 0
    Game.life = 5
    Game.bullet_miss = 0
    Game.end = False

def draw_text(x, y, text, font=GLUT_BITMAP_HELVETICA_18):
    glColor3f(1,1,1)
    glMatrixMode(GL_PROJECTION)
    glPushMatrix()
    glLoadIdentity()
    gluOrtho2D(0, window.width, 0, window.heigth)
    glMatrixMode(GL_MODELVIEW)
    glPushMatrix()
    glLoadIdentity()
    glRasterPos2f(x, y)
    for ch in text:
        glutBitmapCharacter(font, ord(ch))

    glPopMatrix()
    glMatrixMode(GL_PROJECTION)
    glPopMatrix()
    glMatrixMode(GL_MODELVIEW)

def draw_bullet(x,y):
    glPushMatrix()
    glColor(*color.bullet)
    glTranslatef(x,y,50)
    glutSolidCube(10)
    glPopMatrix()

def draw_player():
    glPushMatrix()
    x,y,z,r = Position.player
    glColor(*color.player[1])
    glTranslatef(x,y,z)
    glRotate(r,0,0,1)
    if Game.end:
        glRotate(-90,1,0,0)
    glTranslate(0,0,80)
    glutSolidCube(60)
    glTranslatef(-20,0,-80)
    glColor(*color.player[3])
    gluCylinder(gluNewQuadric(), 5, 10, 60, 10, 10)
    glTranslatef(40,0,0)
    gluCylinder(gluNewQuadric(), 5, 10, 60, 10, 10)
    glTranslate(-20,0,110)
    glRotatef(90, 1, 0, 0)
    glColor(*color.player[4])
    gluCylinder(gluNewQuadric(), 10, 5, 80, 10, 10)
    glTranslatef(-20,0,0)
    glColor(*color.player[2])
    gluCylinder(gluNewQuadric(), 10, 5, 80, 10, 10)
    glTranslatef(40,0,0)
    gluCylinder(gluNewQuadric(), 10, 5, 80, 10, 10)
    glColor(*color.player[0])
    glRotatef(90, 1, 0, 0)
    glTranslate(-20,0,-20)
    gluSphere(gluNewQuadric(), 20, 10, 10)
    glPopMatrix()


def draw_enemies(x,y,z):
    global enemie_scale
    glPushMatrix()
    scale = 0.5+abs(math.sin(math.radians(enemie_scale)))/2
    glTranslate(x,y,z)
    glScalef(scale,scale,scale)
    glColor(1,0,0)
    gluSphere(gluNewQuadric(), 80, 10, 10)
    glTranslate(0,0,80)
    glColor(0,0,0)
    gluSphere(gluNewQuadric(), 30, 10, 10)
    glPopMatrix()


def draw_Floor():
    grid_len = window.grid_len

    glBegin(GL_QUADS)
    # Walls
    wall_heigth = 100
    walls = (
        (1,-1,1,1),
        (1,1,-1,1),
        (-1,-1,-1,1),
        (-1,-1,1,-1),
    )
    for i,(x1,y1,x2,y2) in enumerate(walls):
        glColor3f(*color.walls[i])
        glVertex3f(x1*grid_len, y1*grid_len, 0)
        glVertex3f(x1*grid_len, y1*grid_len, wall_heigth)
        glVertex3f(x2*grid_len, y2*grid_len, wall_heigth)
        glVertex3f(x2*grid_len, y2*grid_len, 0)

    # Floor
    sg_w,sg_h = 14, 10
    w,h = grid_len*2/sg_w, grid_len*2/sg_h
    s1,s2 = -grid_len,grid_len
    for x in range(sg_w):
        for y in range(sg_h):
            glColor3f(*color.floor[(x+y)%2])
            glVertex3f(s1 + x*w, s2 - y*h, 0)
            glVertex3f(s1 + x*w + w, s2 - y*h, 0)
            glVertex3f(s1 + x*w + w, s2 - y*h - h, 0)
            glVertex3f(s1 + x*w, s2 - y*h - h, 0)
    glEnd()

# Keyboard Input
def keyboardListener(key, x, y):
    wall = window.grid_len-20
    x,y,z,r = Position.player
    step = 10
    # Forward Movement
    if key == b'w':
        x= max(min(x+step*math.sin(math.radians(r)),wall),-wall)
        y= min(max(y-step*math.cos(math.radians(r)),-wall),wall)

    # Backward Movement
    if key == b's':
        x= min(max(x-step*math.sin(math.radians(r)),-wall),wall)
        y= max(min(y+step*math.cos(math.radians(r)),wall),-wall)

    # Gun Rotation
    if not Game.cheat_mode and key == b'a': r+=5
    if not Game.cheat_mode and key == b'd': r-=5

    Position.player = (x,y,z,r%360)

    # Cheat Mode
    if key == b'c': Game.cheat_mode = not Game.cheat_mode

    # Cheat Camera
    if Game.cheat_mode and key == b'v':
        state = window.cemera_state
        if window.cam_v==(0,0) or state==0 or state==2: state = 3
        window.cemera_state = 4-state

    # Game Reset
    if key == b'r': restart()
    if key == b'p': Game.pause = not Game.pause

# Arrow keys
def specialKeyListener(key, x, y):
    if window.cemera_state !=0: return

    r = window.grid_len-20
    x, y, z, t = window.camera_pos
    if key == GLUT_KEY_UP: z+=5
    if key == GLUT_KEY_DOWN: z-=5
    if key == GLUT_KEY_LEFT: t += 5
    if key == GLUT_KEY_RIGHT: t -= 5

    x = math.sin(math.radians(t))*r
    y = math.cos(math.radians(t))*r
    window.camera_pos = (x, y, z, t%360)

#Mouse input
def mouseListener(button, state, x, y):
    #  Bullet fire
    if button == GLUT_LEFT_BUTTON and state == GLUT_DOWN:
        x,y,z,r = Position.player
        Position.bullet.append((x,y,r))
        # First Person view
    if button == GLUT_RIGHT_BUTTON and state == GLUT_DOWN: window.cemera_state = (window.cemera_state+1)%3

# Camra View
def setupCamera():
    glMatrixMode(GL_PROJECTION)
    glLoadIdentity()
    gluPerspective(fovY, window.width/window.heigth, 0.1, 1500)
    glMatrixMode(GL_MODELVIEW)
    glLoadIdentity()

    # Camera Position
    if window.cemera_state==0:
        x, y, z, t = window.camera_pos
        gluLookAt(x, y, z,
                0, 0, 0,
                0, 0, 1)
    elif window.cemera_state==1:
        x, y, z, r = Position.player
        x2= x+200*math.sin(math.radians(r))
        y2= y-200*math.cos(math.radians(r))
        window.cam_v = (x2,y2)
        gluLookAt(x, y, z+180,
                x2, y2, 0,
                0, 0, 1)
    elif window.cemera_state==2:
        x, y, z, r = Position.player
        x2= x+200*math.sin(math.radians(r))
        y2= y-200*math.cos(math.radians(r))
        x= x-40*math.sin(math.radians(r))
        y= y+40*math.cos(math.radians(r))
        gluLookAt(x, y, z+200,
                x2, y2, 0,
                0, 0, 1)
    elif window.cemera_state==3:
        x, y, z, r = Position.player
        x2,y2 = window.cam_v
        gluLookAt(x, y, z+180,
                x2, y2, 0,
                0, 0, 1)


def idle():
    time.sleep(1/100)
    if Game.end: return

    if Game.cheat_mode:
        x,y,z,r = Position.player
        r = (r+3)%360
        Position.player = (x,y,z,r)
        for i in range(5):
            ex,ey,ez = Position.enemies[i]
            dx = abs(x-ex)
            dy = abs(y-ey)
            if dx==0: dx=0.001
            t = math.degrees(math.atan(dy/dx))
            if ex<x and y<=ey: t = 180 - t
            elif ex<x and ey<y: t = 180 + t
            elif x<ex and ey<y: t = -t
            t = (t+90)%360
            if abs(abs(t)-abs(r))<1.5:
                Position.bullet.append((x,y,r))

    global enemie_scale
    enemie_scale = (enemie_scale+1)%360
    for i in range(5):
        x,y,z = Position.enemies[i]
        x0,y0,z0,r = Position.player
        if abs(x-x0)<35 and abs(y-y0)<35:
            Game.life -= 1
            Position.enemies[i] = (random.randint(-window.grid_len+50,window.grid_len-50),random.randint(-window.grid_len+50,window.grid_len-50),0)
            continue
        speed = 0.3
        Position.enemies[i] = (x+speed if(abs(x+1-x0)<abs(x-x0)) else x-speed,y+speed if(abs(y+1-y0)<abs(y-y0)) else y-speed,0)

    get_bullet = len(Position.bullet)
    for _ in range(get_bullet):
        x,y,r = Position.bullet.popleft()
        if x<=-window.grid_len or window.grid_len<=x or y<=-window.grid_len or window.grid_len<=y:
            Game.bullet_miss+=1
            continue
        flag = False
        for i in range(5):
            ex,ey,ez = Position.enemies[i]
            if abs(x-ex)<30 and abs(y-ey)<30:
                Position.enemies[i] = (random.randint(-window.grid_len+50,window.grid_len-50),random.randint(-window.grid_len+50,window.grid_len-50),0)
                flag = True
                Game.score+=1
                break
        if flag: continue
        speed = 20
        x2= x+speed*math.sin(math.radians(r))
        y2= y-speed*math.cos(math.radians(r))
        Position.bullet.append((x2,y2,r))

    if Game.life<=0 or Game.bullet_miss>=10:
        Game.end = True
        window.cemera_state = 0

    glutPostRedisplay()

# Environment
def showScreen():
    glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT)
    glLoadIdentity()
    glViewport(0, 0, window.width, window.heigth)
    setupCamera()

    # Game floor
    draw_Floor()
    draw_player()
    if Game.end:
        draw_text(10, 770, f"Game Is Over. Your Score Is: {Game.score}.")
        draw_text(10, 740, "Press 'R' To Restart The Game.")
    else:
        for x,y,z in Position.enemies:
            draw_enemies(x,y,z)
        get_bullets = len(Position.bullet)
        for _ in range(get_bullets):
            x,y,r = Position.bullet.popleft()
            draw_bullet(x,y)
            Position.bullet.append((x,y,r))
        # Display of game info
        draw_text(10, 770, f"player Life Remaining: {Game.life}")
        draw_text(10, 740, f"Game Score: {Game.score}")
        draw_text(10, 710, f"Player Bullet Missed: {Game.bullet_miss}")

    glutSwapBuffers()


def main():
    glutInit()
    glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB | GLUT_DEPTH)
    glutInitWindowSize(window.width, window.heigth)
    glutInitWindowPosition(0, 0)
    wind = glutCreateWindow(b"LAB - 03")

    glutDisplayFunc(showScreen)
    glutKeyboardFunc(keyboardListener)
    glutSpecialFunc(specialKeyListener)
    glutMouseFunc(mouseListener)
    glutIdleFunc(idle)
    glutMainLoop()

if __name__ == "__main__":
    main()